import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Check, ChefHat, ClipboardList, Wallet, Smartphone, Plus, ShoppingBag } from "lucide-react"
import { MarketingShell } from "@/components/marketing/marketing-shell"
import { ProductFlow } from "@/components/marketing/product-flow"
const benefits = [
  { icon: ClipboardList, title: "Pedidos no lugar certo", text: "Veja o que chegou, o que está sendo preparado e o que já foi entregue." },
  { icon: ChefHat, title: "Cozinha bem informada", text: "Sabores, quantidades e observações junto de cada pedido." },
  { icon: Wallet, title: "Caixa organizado", text: "Registre as vendas e acompanhe os pagamentos da sua operação." },
]
function StartButton({ className = "" }: { className?: string }) { return <Link href="/teste-gratis" className={`inline-flex items-center justify-center gap-2 rounded-xl bg-orange-600 px-6 py-4 font-bold text-white transition hover:bg-orange-700 ${className}`}>Começar meu teste grátis <ArrowRight aria-hidden="true" className="h-5 w-5" /></Link> }
function MenuPhone() {
  return <div className="w-[218px] shrink-0 rounded-[34px] border-[7px] border-stone-900 bg-white p-3 text-stone-900 shadow-2xl sm:w-[250px]" aria-label="Exemplo ilustrativo de cardápio no celular"><div aria-hidden="true" className="mx-auto mb-5 h-2 w-16 rounded-full bg-stone-900" /><div className="rounded-xl bg-orange-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-orange-700">Seu cardápio</p><p className="mt-2 text-xl font-black">Delícias da Casa</p><span className="mt-2 inline-block text-[10px] font-bold text-emerald-700">● Aberto para pedidos</span></div><div className="my-4 flex gap-2 text-[10px] font-bold"><span className="rounded-full bg-orange-600 px-3 py-2 text-white">Combos</span><span className="rounded-full bg-stone-100 px-3 py-2">Bebidas</span></div><div className="rounded-xl border border-stone-100 p-3"><div className="relative h-24 overflow-hidden rounded-lg"><Image src="/marketing/atendimento-saborflow.webp" alt="Salgados e atendimento em uma lanchonete — imagem ilustrativa" fill sizes="220px" className="object-cover object-bottom" /></div><p className="mt-3 text-sm font-black">Combo de salgados</p><p className="mt-1 text-[10px] leading-4 text-stone-500">Escolha seus sabores favoritos.</p><div className="mt-3 flex items-center justify-between"><span className="text-sm font-bold">R$ 24,00</span><Plus aria-hidden="true" className="h-6 w-6 rounded-full bg-orange-600 p-1 text-white" /></div></div><div className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-stone-900 py-3 text-[11px] font-bold text-white"><ShoppingBag aria-hidden="true" className="h-3 w-3" />Meu pedido</div><p className="my-2 text-center text-[9px] text-stone-400">Prévia ilustrativa</p></div>
}
export function MarketingHome() {
  return <MarketingShell><main>
    <section className="overflow-hidden bg-gradient-to-b from-orange-50 to-[#fffaf3]">
      <div className="mx-auto grid max-w-7xl items-center gap-10 px-4 pb-16 pt-12 sm:px-6 lg:grid-cols-[1fr_1.05fr] lg:gap-16 lg:px-8 lg:py-20">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-orange-200 bg-white px-4 py-2 text-xs font-bold text-orange-800"><span className="h-2 w-2 rounded-full bg-orange-600" />Para quem faz a comida e cuida do negócio</span><h1 className="mt-6 text-4xl font-black leading-[1.08] tracking-tight text-stone-950 sm:text-5xl xl:text-6xl">Seu negócio merece<br /><span className="text-orange-600">uma rotina mais leve.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-stone-600">Do cardápio no celular ao pedido na cozinha. Organize as vendas, acompanhe o caixa e comece com o que sua loja precisa.</p><StartButton className="mt-8 w-full sm:w-auto" /><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-stone-600">{["7 dias grátis", "Sem cartão", "Gestão básica, sem IA"].map(item => <span key={item} className="flex items-center gap-1"><Check aria-hidden="true" className="h-4 w-4 text-orange-600" />{item}</span>)}</div><Link href="/demo" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-stone-600 underline underline-offset-4">Só quero conhecer a demonstração <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div>
        <div className="relative mx-auto w-full max-w-xl pb-16 pl-12 sm:pb-20 sm:pl-16"><div className="relative aspect-[4/5] overflow-hidden rounded-[36px] sm:aspect-square"><Image src="/marketing/atendimento-saborflow.webp" alt="Cena ilustrativa de uma dona de lanchonete usando um tablet no atendimento" fill priority sizes="(max-width: 1024px) 90vw, 550px" className="object-cover" /></div><div className="absolute bottom-0 left-0 origin-bottom-left scale-[0.78] sm:scale-[0.88]"><MenuPhone /></div><div className="absolute bottom-8 right-0 max-w-[170px] rounded-2xl border border-orange-100 bg-white p-4 shadow-lg sm:bottom-10 sm:max-w-[205px]"><span className="flex items-center gap-2 text-xs font-bold text-emerald-700"><Check className="h-4 w-4" aria-hidden="true" />Tudo no mesmo fluxo</span><p className="mt-2 text-sm font-black">Cliente escolhe.<br />Sua equipe prepara.</p></div></div>
      </div>
    </section>
    <section className="border-y border-orange-100 bg-white px-4 py-6"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-x-7 gap-y-3 text-sm font-bold text-stone-500"><span className="text-stone-900">Feito para sua rotina:</span>{["Salgaderias", "Lanchonetes", "Restaurantes", "Pizzarias", "Açaí e sorvetes", "Confeitarias"].map(item => <span key={item}>{item}</span>)}</div></section>
    <section id="recursos" className="mx-auto max-w-7xl scroll-mt-28 px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold text-orange-700">O simples que faz diferença</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Menos trabalho para organizar.<br />Mais atenção para atender.</h2></div><div className="mt-9 grid gap-5 md:grid-cols-3">{benefits.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-stone-200 bg-white p-7"><Icon aria-hidden="true" className="h-8 w-8 text-orange-600" /><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-stone-600">{text}</p></article>)}</div></section>
    <section id="como-funciona" className="scroll-mt-28 bg-white px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold text-orange-700">Veja o caminho do pedido</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Da primeira escolha ao caixa.</h2><p className="mt-4 text-stone-600">Selecione uma etapa e veja como as informações acompanham o pedido.</p><ProductFlow /></div></section>
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="relative rounded-[32px] bg-orange-100 px-6 pb-0 pt-10"><div className="mx-auto flex w-fit items-center gap-5 pb-8"><MenuPhone /><div className="hidden max-w-[140px] sm:block"><Smartphone aria-hidden="true" className="h-9 w-9 text-orange-700" /><p className="mt-4 text-xl font-black">Sua loja na palma da mão.</p><p className="mt-3 text-sm leading-6 text-stone-600">Produtos por categoria e sabores fáceis de escolher.</p></div></div></div><div><p className="text-sm font-bold text-orange-700">Com a cara da sua empresa</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Um cardápio que facilita a escolha.</h2><p className="mt-5 text-lg leading-8 text-stone-600">Cadastre seus produtos, organize as categorias e defina os complementos. Seu cliente vê tudo pelo celular.</p><ul className="mt-6 space-y-3 text-stone-700">{["Fotos e preços dos produtos", "Sabores e complementos obrigatórios", "Entrega ou retirada", "Link para compartilhar com seus clientes"].map(item => <li className="flex gap-3" key={item}><Check aria-hidden="true" className="h-5 w-5 shrink-0 text-orange-600" />{item}</li>)}</ul><StartButton className="mt-8" /></div></section>
    <section className="bg-stone-950 px-4 py-16 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold text-orange-400">Comece pelo necessário</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Primeiro sua rotina.<br />Depois, os próximos passos.</h2><p className="mt-5 max-w-xl text-base leading-8 text-stone-300">O teste básico reúne produtos, pedidos, PDV, cozinha e caixa. Você cadastra sua loja e experimenta sem precisar configurar uma inteligência artificial.</p><p className="mt-4 text-sm leading-6 text-stone-400">1 loja · 1 acesso · até 30 produtos. Sem IA e integrações externas no teste. Ao final dos 7 dias, o acesso é pausado.</p></div><div className="rounded-3xl bg-white p-7 text-stone-900 sm:p-9"><span className="text-sm font-bold text-orange-700">É rápido para começar</span><h3 className="mt-3 text-2xl font-black">Vamos conhecer seu negócio?</h3><ol className="mt-6 space-y-4 text-sm text-stone-600"><li><strong className="text-stone-900">1. Conte sobre sua loja</strong><br />Seu ramo, sua experiência e a quantidade de pedidos.</li><li><strong className="text-stone-900">2. Crie seu acesso</strong><br />Guarde seus dados para continuar o teste depois.</li><li><strong className="text-stone-900">3. Comece a organizar</strong><br />Cadastre os produtos e registre a primeira venda.</li></ol><StartButton className="mt-7 w-full" /><p className="mt-3 text-center text-xs text-stone-500">Sem cartão e sem cobrança automática.</p></div></div></section>
    <section className="mx-auto max-w-3xl px-4 py-16 sm:px-6"><h2 className="text-center text-3xl font-black">Antes de começar</h2><div className="mt-8 divide-y divide-stone-200">{[["Preciso saber usar um sistema?", "Não precisa ter experiência. O cadastro pergunta como você trabalha hoje, e o painel básico reúne as áreas principais da operação."], ["O teste vem com IA?", "Não. O teste grátis é de gestão básica. A IA é um recurso adicional, com ativação separada."], ["Preciso cadastrar cartão?", "Não. O teste dura 7 dias e não gera cobrança automática. Depois, o acesso é pausado e você pode consultar os planos."], ["O que posso usar no teste?", "Produtos, categorias, complementos, pedidos, PDV, cozinha, clientes e caixa. Impressão externa, integrações, emissão fiscal e domínio próprio não fazem parte do teste."], ["Já tenho um teste. Como volto ao painel?", "Abra Testar grátis e selecione Já iniciei meu teste. Entre com o mesmo e-mail e senha para retomar seu ambiente ativo."]].map(([question, answer]) => <details key={question} className="py-5"><summary className="cursor-pointer font-bold text-stone-900">{question}</summary><p className="mt-3 text-sm leading-7 text-stone-600">{answer}</p></details>)}</div><p className="mt-8 text-center text-sm text-stone-500">Quer comparar as opções? <Link className="font-bold text-orange-700 underline" href="/planos">Veja os planos disponíveis.</Link></p></section>
  </main></MarketingShell>
}
