"use client"
import { useState } from "react"
import { Check, ChevronRight, ShoppingBag, ChefHat, Truck, Wallet } from "lucide-react"
const stages = [
  { title: "O cliente escolhe", icon: ShoppingBag, description: "No celular, ele vê os produtos, escolhe os sabores e monta o pedido.", status: "Pedido recebido", color: "bg-orange-100 text-orange-800", detail: "2 combos · Frango e queijo · Refrigerante", next: "Conferir pedido" },
  { title: "A equipe prepara", icon: ChefHat, description: "O pedido chega organizado, com quantidades, complementos e observações.", status: "Em preparo", color: "bg-blue-100 text-blue-800", detail: "Observação: separar os sabores em embalagens diferentes.", next: "Marcar como pronto" },
  { title: "Sai para o cliente", icon: Truck, description: "Acompanhe a retirada ou a entrega e atualize o andamento do pedido.", status: "Pronto para retirada", color: "bg-emerald-100 text-emerald-800", detail: "Retirada no balcão · Hoje, às 18h30", next: "Concluir pedido" },
  { title: "Você acompanha", icon: Wallet, description: "Consulte as vendas e os pagamentos registrados no caixa.", status: "Concluído", color: "bg-stone-100 text-stone-700", detail: "Pagamento recebido em dinheiro · R$ 48,00", next: "Consultar caixa" },
] as const
export function ProductFlow() {
  const [active, setActive] = useState(0)
  const stage = stages[active]
  return <div className="mt-10 grid items-start gap-7 lg:grid-cols-2">
    <div role="tablist" aria-label="Etapas do pedido" className="grid gap-3">{stages.map(({ title, icon: Icon, description }, index) => <button key={title} role="tab" id={`flow-tab-${index}`} aria-selected={active === index} aria-controls="flow-panel" tabIndex={active === index ? 0 : -1} onClick={() => setActive(index)} onKeyDown={event => { let next = index; if (["ArrowDown", "ArrowRight"].includes(event.key)) next = (index + 1) % stages.length; else if (["ArrowUp", "ArrowLeft"].includes(event.key)) next = (index + stages.length - 1) % stages.length; else if (event.key === "Home") next = 0; else if (event.key === "End") next = stages.length - 1; else return; event.preventDefault(); setActive(next); document.getElementById(`flow-tab-${next}`)?.focus() }} className={`flex gap-4 rounded-2xl border p-5 text-left transition ${active === index ? "border-orange-400 bg-orange-50" : "border-stone-200 bg-white hover:border-orange-200"}`}><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${active === index ? "bg-orange-600 text-white" : "bg-stone-100 text-stone-500"}`}><Icon className="h-5 w-5" aria-hidden="true" /></span><span><span className="block text-lg font-bold">{index + 1}. {title}</span><span className="mt-1 block text-sm leading-6 text-stone-600">{description}</span></span></button>)}</div>
    <div id="flow-panel" role="tabpanel" aria-labelledby={`flow-tab-${active}`} tabIndex={0} className="rounded-[28px] border border-stone-200 bg-[#fffaf4] p-5 sm:p-9"><div className="flex items-center justify-between gap-4"><span className="font-black">SaborFlow <span className="font-normal text-stone-400">/ Pedidos</span></span><span className="text-xs text-stone-500">Exemplo ilustrativo</span></div><div className="mt-8 rounded-2xl bg-white p-6 shadow-lg shadow-stone-900/5"><div className="flex items-center justify-between"><span className="text-2xl font-black">Pedido #102</span><span className="text-sm text-stone-500">18:15</span></div><span className={`mt-4 inline-flex rounded-full px-3 py-1 text-xs font-bold ${stage.color}`}>{stage.status}</span><div className="my-6 border-y border-stone-100 py-5"><p className="font-bold">2 × Combo de salgados</p><p className="mt-2 text-sm leading-6 text-stone-500">{stage.detail}</p></div><div className="flex justify-between font-bold"><span>Total</span><span>R$ 48,00</span></div><div className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-stone-950 px-4 py-3 text-sm font-bold text-white"><Check className="h-4 w-4" aria-hidden="true" />{stage.next}</div></div><p className="mt-6 flex items-center gap-2 text-sm font-semibold text-stone-600"><ChevronRight className="h-4 w-4 text-orange-600" aria-hidden="true" />{stage.title}</p></div>
  </div>
}
