"use client"
import type { Order, StoreSettings } from "@/lib/types"

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value)
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char] || char))

export function orderTicketHtml(order: Order, settings?: Pick<StoreSettings, "storeName" | "address" | "timeZone">, mode: "kitchen" | "customer" = "customer") {
  const items = order.items.map((item) => {
    const modifiers = (item.modifiers || []).map((modifier) => `<div class="choice">${escapeHtml(modifier.groupName)}: ${escapeHtml(modifier.optionName)}${mode === "customer" && !modifier.included && modifier.priceDelta > 0 ? ` (+${money(modifier.priceDelta)})` : ""}</div>`).join("")
    return `<tr><td><strong>${item.quantity}x ${escapeHtml(item.name)}</strong>${modifiers}</td><td style="text-align:right">${mode === "customer" ? money(item.subtotal) : ""}</td></tr>`
  }).join("")
  const receive = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: settings?.timeZone || "America/Sao_Paulo" }).format(new Date(order.requestedFor))
  const created = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: settings?.timeZone || "America/Sao_Paulo" }).format(new Date(order.createdAt))
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(order.code)}</title><style>@page{size:80mm auto;margin:2mm}*{box-sizing:border-box}body{font:600 16px Arial,sans-serif;margin:0;width:100%;color:#000;overflow-wrap:anywhere}.c{text-align:center}.b{font-weight:900}.big{font-size:25px}hr{border:0;border-top:2px dashed #000;margin:8px 0}table{width:100%;border-collapse:collapse}td{padding:5px 0;vertical-align:top}.small{font-size:12px}.choice{font-size:15px;font-weight:600;padding:2px 0 0 8px}.warn{font-size:19px;font-weight:900;border:2px solid #000;padding:6px;text-align:center;margin:7px 0}.section{font-size:18px;font-weight:900;margin:7px 0 3px}table td:last-child{white-space:nowrap}</style></head><body><div class="c b">${escapeHtml(settings?.storeName || "SaborFlow")}</div><div class="c big b">${escapeHtml(order.code)}</div><div class="c small">${escapeHtml(order.reference)}</div><hr/><div>FEITO EM: ${created}</div><div class="warn">RECEBER EM: ${receive}</div><div class="warn">${order.type === "delivery" ? "ENTREGA" : "RETIRADA"} · ${order.scheduled ? "AGENDADO" : "IMEDIATO"}</div><div class="b">CLIENTE: ${escapeHtml(order.customer.name)}</div>${order.customer.phone ? `<div>Telefone: ${escapeHtml(order.customer.phone)}</div>` : ""}${order.type === "delivery" ? `<div class="section">ENDEREÇO DE ENTREGA</div><div class="b">${escapeHtml(order.customer.address)}, ${escapeHtml(order.customer.number || "")}${order.customer.complement ? `, ${escapeHtml(order.customer.complement)}` : ""}${order.customer.district ? ` - ${escapeHtml(order.customer.district)}` : ""}${order.customer.city ? `, ${escapeHtml(order.customer.city)}` : ""}</div>` : ""}<hr/><div class="section">ITENS DO PEDIDO</div><table>${items}</table>${order.notes ? `<hr/><div class="warn">OBSERVAÇÕES</div><div class="b">${escapeHtml(order.notes)}</div>` : ""}${mode === "customer" ? `<hr/><table><tr><td>Subtotal</td><td style="text-align:right">${money(order.subtotal)}</td></tr>${order.discount ? `<tr><td>Desconto</td><td style="text-align:right">-${money(order.discount)}</td></tr>` : ""}${order.cashbackUsed ? `<tr><td>Cashback</td><td style="text-align:right">-${money(order.cashbackUsed)}</td></tr>` : ""}${order.deliveryFee ? `<tr><td>Entrega</td><td style="text-align:right">${money(order.deliveryFee)}</td></tr>` : ""}<tr class="b"><td>TOTAL</td><td style="text-align:right">${money(order.total)}</td></tr></table><div>Pagamento: ${order.paymentMethod === "pix" ? "PIX" : order.paymentMethod === "cash" ? "DINHEIRO" : "CARTÃO"}${order.changeFor ? ` · Troco para ${escapeHtml(order.changeFor)}` : ""}</div>` : ""}<hr/><div class="c small">${escapeHtml(settings?.address || "")}</div><script>window.onload=()=>{window.print();setTimeout(()=>window.close(),300)}</script></body></html>`
}

export function printOrder(order: Order, settings?: Pick<StoreSettings, "storeName" | "address" | "timeZone">, mode: "kitchen" | "customer" = "customer") {
  const popup = window.open("", "_blank", "width=480,height=800")
  if (!popup) throw new Error("O navegador bloqueou a janela de impressão.")
  popup.document.open()
  popup.document.write(orderTicketHtml(order, settings, mode))
  popup.document.close()
}
