"use client"
import { useState, type FormEvent } from "react"
import type { StoreSettings } from "@/lib/types"
const input = "mt-1 w-full rounded-xl border border-stone-300 px-3 py-3 text-sm focus:border-orange-500 focus:outline-none focus:ring-2 focus:ring-orange-100"
export function BasicTrialSettings({ settings, onSettingsChanged }: { settings: StoreSettings; onSettingsChanged: (settings: StoreSettings) => void }) {
  const [draft, setDraft] = useState(() => ({ storeName: settings.storeName, phone: settings.phone, address: settings.address, storeDistrict: settings.storeDistrict, city: settings.city, state: settings.state, zipCode: settings.zipCode, businessHours: settings.businessHours, acceptingOrders: settings.acceptingOrders, pickupEnabled: settings.pickupEnabled, deliveryEnabled: settings.deliveryEnabled, fixedDeliveryFee: settings.fixedDeliveryFee, cashEnabled: settings.cashEnabled, cardEnabled: settings.cardEnabled }))
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState("")
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage("")
    try {
      if (!draft.pickupEnabled && !draft.deliveryEnabled) throw new Error("Escolha retirada ou entrega.")
      if (!draft.cashEnabled && !draft.cardEnabled) throw new Error("Escolha uma forma de pagamento.")
      const response = await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, deliveryPricingMode: "fixed" }) })
      const data = await response.json().catch(() => ({}))
      if (!response.ok || !data.settings) throw new Error(data.error || "Não foi possível salvar.")
      onSettingsChanged(data.settings); setMessage("Configurações salvas. Confira o link da loja.")
    } catch (error) { setMessage(error instanceof Error ? error.message : "Falha de conexão. Tente novamente.") } finally { setBusy(false) }
  }
  return <form onSubmit={save} className="mx-auto max-w-4xl space-y-6"><div><h2 className="text-2xl font-black">O básico da sua loja</h2><p className="mt-2 text-sm text-stone-500">Preencha os dados, defina os horários e ative os pedidos quando estiver pronto.</p></div><fieldset disabled={busy} className="space-y-6 disabled:opacity-60"><section className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-bold">Dados e endereço</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{([['storeName', 'Nome da loja'], ['phone', 'Telefone'], ['address', 'Rua e número'], ['storeDistrict', 'Bairro'], ['city', 'Cidade'], ['state', 'Estado (UF)'], ['zipCode', 'CEP']] as const).map(([key, label]) => <label className="text-sm font-semibold" key={key}>{label}<input value={draft[key]} className={input} maxLength={key === 'state' ? 2 : 180} required={['storeName', 'address', 'city', 'state'].includes(key)} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}</div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-bold">Dias e horários</h3><div className="mt-4 space-y-3">{draft.businessHours.map(day => <div className="grid items-center gap-3 rounded-xl bg-stone-50 p-3 sm:grid-cols-[1fr_1fr_1fr]" key={day.day}><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={day.enabled} onChange={e => setDraft({ ...draft, businessHours: draft.businessHours.map(item => item.day === day.day ? { ...item, enabled: e.target.checked } : item) })} />{day.label}</label>{(['open', 'close'] as const).map(key => <label className="text-xs font-semibold" key={key}>{key === 'open' ? 'Abre' : 'Fecha'}<input type="time" className={input} disabled={!day.enabled} required={day.enabled} value={day[key]} onChange={e => setDraft({ ...draft, businessHours: draft.businessHours.map(item => item.day === day.day ? { ...item, [key]: e.target.value } : item) })} /></label>)}</div>)}</div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-bold">Como receber e pagar</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{([['pickupEnabled', 'Retirada na loja'], ['deliveryEnabled', 'Entrega'], ['cashEnabled', 'Dinheiro'], ['cardEnabled', 'Cartão na entrega ou retirada']] as const).map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.checked })} />{label}</label>)}</div>{draft.deliveryEnabled && <label className="mt-4 block text-sm font-semibold">Taxa fixa de entrega (R$)<input type="number" min="0" max="1000" step="0.01" required value={draft.fixedDeliveryFee} className={input} onChange={e => setDraft({ ...draft, fixedDeliveryFee: Number(e.target.value) })} /></label>}<p className="mt-3 text-xs text-stone-500">Os pagamentos são registrados no sistema. Não há cobrança online de cartão neste teste.</p></section>
    <label className="flex items-center gap-3 rounded-2xl border border-orange-200 bg-orange-50 p-5 font-bold"><input type="checkbox" className="h-5 w-5 accent-orange-600" checked={draft.acceptingOrders} onChange={e => setDraft({ ...draft, acceptingOrders: e.target.checked })} />Receber pedidos pelo cardápio</label>
    <button className="rounded-xl bg-orange-600 px-6 py-3 font-bold text-white">{busy ? "Salvando..." : "Salvar configurações"}</button></fieldset>{message && <p role="status" className="rounded-xl bg-white p-4 text-sm">{message}</p>}</form>
}
