"use client"

import { FormEvent, useMemo, useState } from "react"
import { BarChart3, Copy, ExternalLink, Gift, MessageCircle, Plus, Power, Send, Store, TicketPercent } from "lucide-react"
import type { Coupon, CustomerSummary, StoreSettings } from "@/lib/types"

export function MarketingPanel({ coupons: initialCoupons, customers, settings, onSettingsChanged }: { coupons: Coupon[]; customers: CustomerSummary[]; settings: StoreSettings; onSettingsChanged: (settings: StoreSettings) => void }) {
  const [coupons, setCoupons] = useState(initialCoupons)
  const [draft, setDraft] = useState({ code: "", description: "", type: "percent" as "percent" | "fixed", value: "10", minimumOrder: "0" })
  const [segment, setSegment] = useState("all")
  const [bulkText, setBulkText] = useState(() => `Olá! Temos novidades no cardápio da ${settings.storeName} 😋`)
  const [message, setMessage] = useState("")
  const [loyalty, setLoyalty] = useState({ enabled: settings.loyaltyEnabled, points: settings.loyaltyPointsPerReal, rewardPoints: settings.loyaltyRewardPoints, rewardText: settings.loyaltyRewardText })
  const audience = useMemo(() => customers.filter((c) => segment === "all" || c.segment === segment || c.lifecycle === segment), [customers, segment])

  async function addCoupon(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/coupons", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, value: Number(draft.value.replace(",", ".")), minimumOrder: Number(draft.minimumOrder.replace(",", ".")), active: true }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "Erro ao criar cupom."); setCoupons([...coupons, data.coupon]); setDraft({ code: "", description: "", type: "percent", value: "10", minimumOrder: "0" }); setMessage("Cupom criado.") }
  async function toggle(coupon: Coupon) { const response = await fetch(`/api/coupons/${coupon.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !coupon.active }) }); const data = await response.json(); if (response.ok) setCoupons(coupons.map((item) => item.id === coupon.id ? data.coupon : item)) }
  async function saveLoyalty() { const response = await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ loyaltyEnabled: loyalty.enabled, loyaltyPointsPerReal: loyalty.points, loyaltyRewardPoints: loyalty.rewardPoints, loyaltyRewardText: loyalty.rewardText }) }); const data = await response.json(); if (response.ok) { onSettingsChanged(data.settings); setMessage("Programa de fidelidade atualizado.") } }
  function openWhatsApp(customer: CustomerSummary) { const phone = customer.phone.replace(/\D/g, ""); if (!phone) return; window.open(`https://wa.me/${phone}?text=${encodeURIComponent(bulkText)}`, "_blank") }

  return <div className="space-y-5">
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><TicketPercent className="h-5 w-5 text-blue-700"/><h2 className="font-black">Cupons de desconto</h2></div><form onSubmit={addCoupon} className="mt-4 grid gap-3 sm:grid-cols-2"><input required value={draft.code} onChange={(e) => setDraft({ ...draft, code: e.target.value.toUpperCase() })} placeholder="CÓDIGO" className="h-10 rounded-xl border border-gray-200 px-3 text-sm uppercase"/><input value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} placeholder="Descrição" className="h-10 rounded-xl border border-gray-200 px-3 text-sm"/><select value={draft.type} onChange={(e) => setDraft({ ...draft, type: e.target.value as any })} className="h-10 rounded-xl border border-gray-200 bg-white px-3 text-sm"><option value="percent">Percentual (%)</option><option value="fixed">Valor fixo (R$)</option></select><input value={draft.value} onChange={(e) => setDraft({ ...draft, value: e.target.value })} placeholder="Valor" className="h-10 rounded-xl border border-gray-200 px-3 text-sm"/><input value={draft.minimumOrder} onChange={(e) => setDraft({ ...draft, minimumOrder: e.target.value })} placeholder="Pedido mínimo" className="h-10 rounded-xl border border-gray-200 px-3 text-sm"/><button className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-700 text-sm font-black text-white"><Plus className="h-4 w-4"/>Criar cupom</button></form><div className="mt-4 space-y-2">{coupons.map((coupon) => <div key={coupon.id} className="flex items-center gap-3 rounded-xl border border-gray-200 p-3"><div className="min-w-0 flex-1"><p className="font-black">{coupon.code}</p><p className="text-xs text-gray-500">{coupon.type === "percent" ? `${coupon.value}%` : `R$ ${coupon.value.toFixed(2)}`} · mínimo R$ {coupon.minimumOrder.toFixed(2)}</p></div><button onClick={() => navigator.clipboard.writeText(coupon.code)} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><Copy className="h-4 w-4"/></button><button onClick={() => toggle(coupon)} className={`rounded-lg p-2 ${coupon.active ? "text-emerald-600" : "text-gray-400"}`}><Power className="h-4 w-4"/></button></div>)}</div></section>

      <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Gift className="h-5 w-5 text-violet-700"/><h2 className="font-black">Programa de fidelidade</h2></div><div className="mt-4 space-y-3"><label className="flex items-center justify-between rounded-xl border border-gray-200 p-3"><span><strong className="block text-sm">Ativar pontos</strong><small className="text-gray-500">Clientes logados acumulam pontos automaticamente.</small></span><input type="checkbox" checked={loyalty.enabled} onChange={(e) => setLoyalty({ ...loyalty, enabled: e.target.checked })} className="h-5 w-5"/></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-bold uppercase text-gray-500">Pontos por R$ 1</span><input type="number" min="0" step="0.1" value={loyalty.points} onChange={(e) => setLoyalty({ ...loyalty, points: Number(e.target.value) })} className="h-10 w-full rounded-xl border border-gray-200 px-3"/></label><label><span className="mb-1 block text-xs font-bold uppercase text-gray-500">Meta de pontos</span><input type="number" min="1" value={loyalty.rewardPoints} onChange={(e) => setLoyalty({ ...loyalty, rewardPoints: Number(e.target.value) })} className="h-10 w-full rounded-xl border border-gray-200 px-3"/></label></div><textarea value={loyalty.rewardText} onChange={(e) => setLoyalty({ ...loyalty, rewardText: e.target.value })} rows={3} className="w-full rounded-xl border border-gray-200 px-3 py-2 text-sm" placeholder="Benefício do programa"/><button onClick={saveLoyalty} className="h-10 w-full rounded-xl bg-violet-700 text-sm font-black text-white">Salvar fidelidade</button></div></section>
    </div>

    <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Send className="h-5 w-5 text-emerald-700"/><h2 className="font-black">Envio em massa pelo WhatsApp</h2></div><p className="mt-1 text-sm text-gray-500">Selecione um segmento e abra as conversas uma a uma. Para automação real em massa, conecte a API oficial do WhatsApp Business.</p><div className="mt-4 grid gap-3 md:grid-cols-[220px_1fr]"><select value={segment} onChange={(e) => setSegment(e.target.value)} className="h-10 rounded-xl border border-gray-200 bg-white px-3 text-sm"><option value="all">Todos</option><option value="elite">Comprador Elite</option><option value="frequent">Comprador frequente</option><option value="repeat">Comprador repetido</option><option value="active">Ativos</option><option value="sleeping">Dormindo</option><option value="inactive">Inativos</option></select><textarea value={bulkText} onChange={(e) => setBulkText(e.target.value)} rows={2} className="rounded-xl border border-gray-200 px-3 py-2 text-sm"/></div><div className="mt-4 flex flex-wrap gap-2">{audience.slice(0, 50).map((customer) => <button key={customer.key} onClick={() => openWhatsApp(customer)} className="inline-flex items-center gap-1 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700"><MessageCircle className="h-3.5 w-3.5"/>{customer.name}</button>)}</div><p className="mt-3 text-xs text-gray-400">Público selecionado: {audience.length} cliente(s).</p></section>
    <section className="grid gap-4 md:grid-cols-2">
      <article className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Store className="h-5 w-5 text-blue-700"/><h2 className="font-black">Google para o negócio</h2></div><p className="mt-2 text-sm text-gray-500">Centralize o link do Perfil da Empresa e leve clientes para Maps/Pesquisa.</p>{settings.googleBusinessUrl ? <a href={settings.googleBusinessUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex h-10 items-center gap-2 rounded-xl bg-blue-50 px-3 text-sm font-black text-blue-700"><ExternalLink className="h-4 w-4"/>Abrir Perfil da Empresa</a> : <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-700">Configure o link em Configurações → Avaliações e Google.</p>}</article>
      <article className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-violet-700"/><h2 className="font-black">Ferramentas de rastreamento</h2></div><p className="mt-2 text-sm text-gray-500">IDs preparados para Google Analytics e Meta Pixel nas configurações.</p><div className="mt-4 grid gap-2 text-xs"><div className="rounded-xl bg-gray-50 p-3"><strong>Google Analytics:</strong> {settings.googleAnalyticsId || "não configurado"}</div><div className="rounded-xl bg-gray-50 p-3"><strong>Meta Pixel:</strong> {settings.metaPixelId || "não configurado"}</div></div></article>
    </section>
    {message && <div className="rounded-xl bg-blue-50 px-4 py-3 text-sm font-bold text-blue-700">{message}</div>}
  </div>
}
